# Generated by Django 5.2.5 on 2025-09-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("weather", models.CharField(blank=True, max_length=50)),
                ("steps", models.PositiveIntegerField(blank=True, null=True)),
                ("place", models.CharField(blank=True, max_length=50)),
                ("content", models.TextField(blank=True)),
            ],
        ),
    ]
