# Generated by Django 5.2.5 on 2025-09-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Recipe",
            new_name="Walk",
        ),
    ]
