# Generated by Django 5.2.5 on 2025-09-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0002_rename_recipe_walk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walk",
            name="steps",
            field=models.CharField(blank=True),
        ),
    ]
