# Generated by Django 5.2.5 on 2025-09-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0003_alter_walk_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walk",
            name="steps",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
