# Generated by Django 5.2.5 on 2025-09-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0004_alter_walk_steps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="walk",
            old_name="place",
            new_name="endtpoint",
        ),
        migrations.AddField(
            model_name="walk",
            name="startpoint",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
