# Generated by Django 5.2.5 on 2025-09-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0005_rename_place_walk_endtpoint_walk_startpoint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="walk",
            options={"verbose_name": "散歩", "verbose_name_plural": "散歩"},
        ),
        migrations.RemoveField(
            model_name="walk",
            name="endtpoint",
        ),
        migrations.AddField(
            model_name="walk",
            name="distance",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="歩数"
            ),
        ),
        migrations.AlterField(
            model_name="walk",
            name="content",
            field=models.TextField(blank=True, verbose_name="コメント"),
        ),
        migrations.AlterField(
            model_name="walk",
            name="startpoint",
            field=models.CharField(blank=True, max_length=50, verbose_name="到着地"),
        ),
        migrations.AlterField(
            model_name="walk",
            name="steps",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="歩数"
            ),
        ),
        migrations.AlterField(
            model_name="walk",
            name="weather",
            field=models.CharField(blank=True, max_length=50, verbose_name="天気"),
        ),
    ]
