# Generated by Django 5.2.5 on 2025-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0006_alter_walk_options_remove_walk_endtpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="walk",
            name="endpoint",
            field=models.CharField(blank=True, max_length=50, verbose_name="到着地"),
        ),
        migrations.AlterField(
            model_name="walk",
            name="distance",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="距離"
            ),
        ),
        migrations.AlterField(
            model_name="walk",
            name="startpoint",
            field=models.CharField(blank=True, max_length=50, verbose_name="出発地"),
        ),
    ]
