# Generated by Django 5.2.5 on 2025-09-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0007_walk_endpoint_alter_walk_distance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walk",
            name="content",
            field=models.CharField(blank=True, verbose_name="コメント"),
        ),
    ]
