# Generated by Django 5.2.6 on 2025-09-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0008_alter_walk_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="walk",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images/uploaded/"
            ),
        ),
    ]
