# Generated by Django 5.2.6 on 2025-09-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0009_walk_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walk",
            name="distance",
        ),
    ]
