# Generated by Django 5.2.6 on 2025-09-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0011_walk_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walk",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
